main: main.main

name: Foxxi-Essentials
author: CoresSpieler
description: Ist das Essentials-Plugin für Foxxi.net!
version: 1.0

commands:
     vanish:
          description: Macht dich unsichtbar!
     gm:
          description: Erhalte einen angegebenen Modus!
     skull:
          description: Erhalte einen Spieler-Kopf!
     broadcast:
          description: Sendet eine Nachricht an alle Spieler!
          aliases: [bc]
     tp:
          description: Telportiere Spieler!
     tpall:
          description: Teleportiere alle Spieler zu dir!